### ISSUE TITLE
Loader not working

### ISSUE THREAD

**Issue by fiesel** [edwinwebb/pixi-seed#17]
The loading Indicator (Loader) does not work.

I tracked down the problem.

```
  onUpdate(ldr) {
    this.progress = ldr.progress / 100;
  }
```

does not trigger a dispatch so

```
this.unsubscribe = Store.subscribe(() => {
      this.ease += (this.progress - this.ease) * 0.03;
      this.bar.scale.x = this.ease;
    });
```

cant update. By using the AnimationStore you have it updated and therefore the loader will work

**Comment by edwinwebb** [comment]
Thanks for the report. I've had the easing animation be updated AnimationStore and put the loading screen in a ScaledContainer
