### ISSUE TITLE
There should be an option to use Hexi (library bundle for Pixi)

### ISSUE THREAD

**Issue by pajtai** [edwinwebb/pixi-seed#23]
Hexi is a library bundle for Pixi. It'd be great if this could be an option:
https://github.com/kittykatattack/hexi

**Comment by edwinwebb** [comment]
Thanks for introducing me to Hexi. Sadly, Hexi won't play well with `import`. You can probably fork this repo and add hexi manually.

**Comment by pajtai** [comment]
Thanks for the response @edwinwebb . It looks like there are [plans](https://github.com/kittykatattack/hexi/issues/23) to eventually migrate Hexi to NPM.... at that point it'll be an easier match.
