### ISSUE TITLE
How do you load a texture map using a json file?

### ISSUE THREAD

**Issue by pajtai** [edwinwebb/pixi-seed#24]
```javascript
loader.add('images/index.json')
  .load(setup);
```

shows a 404 from entry.js even if I have an images dir with an index.json and a texture map png.

I think I have to import the json and png with an `import` statement but I can't quite figure out how.

I feel like the answer is around https://github.com/edwinwebb/pixi-seed/blob/master/app/displayobjects/Background/Background.js , where I see an image imported and used... but I'm not sure how to import the json definition and associated texture map.

Thanks for any help!

**Comment by edwinwebb** [comment]
You'll need to load the Json with a Webpack loader. Quick Google search
should see you right.

**Comment by pajtai** [comment]
Thanks @edwinwebb .
