### ISSUE TITLE
Doesn't work with PIXI v4+

### ISSUE THREAD

**Issue by luvagarwal** [edwinwebb/pixi-seed#5]
I found the following reference to change postLoaders for v4 but that didn't work out too.
https://gist.github.com/mjackson/ecd3914ebee934f4daf4#gistcomment-1842689

In v4.1.0, webpack gives this warning:

```
./~/pixi.js/bin/pixi.min.js
Critical dependencies:
8:412-419 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/pixi.js/bin/pixi.min.js 8:412-419
```

**Comment by edwinwebb** [comment]
Still doesn't but now uses Pixi 5.
